[package]
name = "cg3-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cmake = "0.1.50"
bindgen = "0.65.1"
cc = "1.0.79"
pkg-config = "0.3.27"


