[package]
name = "cg3"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "staticlib"]

[build-dependencies]
cmake = "0.1.54"
cc = "1.0.79"
pkg-config = "0.3.27"
vcpkg = "0.2.15"

[dependencies]
thiserror = "2"


